on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # adjust if needed

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build JAR
        run: gradle shadowJar
